### ISSUE TITLE
How to change the default anchor points "X" icons?

### ISSUE THREAD

**Issue by Atif-Bashir-1998** [akcyp/lasso-canvas-image#1]

**Comment by akcyp** [comment]
It's not possible, also the package is no longer updated. You might be interested in the new version of this tool written in React: https://github.com/akcyp/react-lasso-select

**Comment by Atif-Bashir-1998** [comment]
> It's not possible, also the package is no longer updated. You might be interested in the new version of this tool written in React: https://github.com/akcyp/react-lasso-select

Thanks @akcyp for replying. Unfortunately I am using Vue :( but I have used the package keeping the default anchor points. Thanks for creating such a nice tool
